In [34]:
import numpy as np
import pandas as pd

In [35]:
data = pd.read_csv('mldata.csv')

In [36]:
## Shows the first 5 rows of the dataframe
data.head()

Logical quotient rating  hackathons  coding skills rating  \
0                        5           0                     6   
1                        7           6                     4   
2                        2           3                     9   
3                        2           6                     3   
4                        2           0                     3   

   public speaking points self-learning capability? Extra-courses did  \
0                       2                       yes                no   
1                       3                        no               yes   
2                       1                        no               yes   
3                       5                        no               yes   
4                       4                       yes                no   

         certifications          workshops reading and writing skills  \
0  information security            testing                       poor   
1     shell programming            testing                  excellent   
2  information security            testing                  excellent   
3         r programming  database security                  excellent   
4         distro making   game development                  excellent   

  memory capability score   Interested subjects   interested career area   \
0                    poor           programming                   testing   
1                  medium            Management          system developer   
2                    poor      data engineering  Business process analyst   
3                    poor              networks                   testing   
4                  medium  Software Engineering          system developer   

  Type of company want to settle in? Taken inputs from seniors or elders  \
0                                BPA                                  no   
1                     Cloud Services                                 yes   
2                product development                                 yes   
3  Testing and Maintainance Services                                 yes   
4                                BPA                                  no   

  Interested Type of Books Management or Technical hard/smart worker  \
0                   Series              Management      smart worker   
1          Autobiographies               Technical       hard worker   
2                   Travel               Technical      smart worker   
3                    Guide              Management      smart worker   
4                   Health               Technical       hard worker   

  worked in teams ever? Introvert      Suggested Job Role  
0                   yes        no  Applications Developer  
1                    no       yes  Applications Developer  
2                    no        no  Applications Developer  
3                   yes       yes  Applications Developer  
4                   yes        no  Applications Developer

In [37]:
## Number of rows and columns
data.shape

(6901, 20)

In [38]:
## Getting some informations about the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6901 entries, 0 to 6900
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype 
---  ------                               --------------  ----- 
 0   Logical quotient rating              6901 non-null   int64 
 1   hackathons                           6901 non-null   int64 
 2   coding skills rating                 6901 non-null   int64 
 3   public speaking points               6901 non-null   int64 
 4   self-learning capability?            6901 non-null   object
 5   Extra-courses did                    6901 non-null   object
 6   certifications                       6901 non-null   object
 7   workshops                            6901 non-null   object
 8   reading and writing skills           6901 non-null   object
 9   memory capability score              6901 non-null   object
 10  Interested subjects                  6901 non-null   object
 11  interested career area               6901 n

In [39]:
## Checking for missing values
data.isnull().sum(axis=0)

Logical quotient rating                0
hackathons                             0
coding skills rating                   0
public speaking points                 0
self-learning capability?              0
Extra-courses did                      0
certifications                         0
workshops                              0
reading and writing skills             0
memory capability score                0
Interested subjects                    0
interested career area                 0
Type of company want to settle in?     0
Taken inputs from seniors or elders    0
Interested Type of Books               0
Management or Technical                0
hard/smart worker                      0
worked in teams ever?                  0
Introvert                              0
Suggested Job Role                     0
dtype: int64

In [40]:
## statistical Measures of the dataset
data.describe()

Logical quotient rating   hackathons  coding skills rating  \
count              6901.000000  6901.000000           6901.000000   
mean                  4.991016     2.999710              5.010723   
std                   2.577704     2.010191              2.568347   
min                   1.000000     0.000000              1.000000   
25%                   3.000000     1.000000              3.000000   
50%                   5.000000     3.000000              5.000000   
75%                   7.000000     5.000000              7.000000   
max                   9.000000     6.000000              9.000000   

       public speaking points  
count             6901.000000  
mean                 4.988263  
std                  2.599500  
min                  1.000000  
25%                  3.000000  
50%                  5.000000  
75%                  7.000000  
max                  9.000000

    Visualization for Categorical Variables

In [41]:
print(data["interested career area "].value_counts())

interested career area 
system developer            1178
security                    1177
Business process analyst    1154
developer                   1145
testing                     1128
cloud computing             1119
Name: count, dtype: int64


In [42]:
print(data['Suggested Job Role'].value_counts())

Suggested Job Role
Network Security Engineer                    630
Software Engineer                            590
UX Designer                                  589
Software Developer                           587
Database Developer                           581
Software Quality Assurance (QA) / Testing    571
Web Developer                                570
CRM Technical Developer                      567
Technical Support                            565
Systems Security Administrator               562
Applications Developer                       551
Mobile Applications Developer                538
Name: count, dtype: int64


In [43]:
print(data.columns)

Index(['Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'self-learning capability?',
       'Extra-courses did', 'certifications', 'workshops',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'Interested Type of Books',
       'Management or Technical', 'hard/smart worker', 'worked in teams ever?',
       'Introvert', 'Suggested Job Role'],
      dtype='object')


                          Encoding the categorical features

In [44]:
## encoding "self-learning capability?" column.
data.replace({'self-learning capability?':{'yes':1,'no':1}},inplace=True)



## encoding "Extra-courses did" column.
data.replace({'Extra-courses did':{'yes':1,'no':1}},inplace=True)



## encoding "certifications" column.
data.replace({'certifications':{'r programming' : 0,
'information security': 1,
'shell programming' : 2,
'machine learning' : 3,
'full stack': 4,
'hadoop' : 5,
'python' : 6,
'distro making' : 7,
'app development' : 8
}},inplace=True)



## encoding "workshops" column.
data.replace({'workshops':{'database security' :0,
'system designing' : 1,
'web technologies' : 2,
'hacking' : 3,
'testing' : 4,
'data science' : 5,
'game development' : 6,
'cloud computing' : 7
}},inplace=True)



## encoding "reading and writing skills" column.
data.replace({'reading and writing skills':{'poor':0,'medium':1, 'excellent':2}},inplace=True)



## encoding "memory capability score" column.
data.replace({'memory capability score':{'poor':0,'medium':1, 'excellent':2}},inplace=True)



## encoding "Interested subjects" column.
data.replace({'Interested subjects':{'Software Engineering': 0, 'IOT': 1, 'cloud computing': 2, 'programming': 3, 'networks': 4,
    'Computer Architecture': 5, 'data engineering': 6, 'hacking': 7, 'Management': 8, 'parallel computing': 9}},inplace=True)



## encoding "interested career area" column.
data.replace({'interested career area ':{'system developer': 0, 'security': 1, 'Business process analyst': 2, 'developer': 3, 'testing': 4,
    'cloud computing': 5}},inplace=True)



## encoding "Type of company want to settle in?" column.
data.replace({'Type of company want to settle in?':{'Service Based': 0, 'Web Services': 1, 'BPA': 2, 'Testing and Maintainance Services': 3,
    'Product based': 3, 'Finance': 4, 'Cloud Services': 5, 'product development': 6,
    'Sales and Marketing': 7, 'SAaS services': 8}},inplace=True)



## encoding "Taken inputs from seniors or elders" column.
data.replace({'Taken inputs from seniors or elders':{'yes': 1, 'no': 0}},inplace=True)



## encoding "Interested Type of Books" column.
data.replace({'Interested Type of Books':{'Guide': 0, 'Health': 1, 'Self help': 2, 'Horror': 3, 'Biographies': 4, 'Science fiction': 5,
    'Satire': 6, 'Childrens': 7, 'Autobiographies': 8, 'Prayer books': 9, 'Fantasy': 10, 'Journals': 11,
    'Trilogy': 12, 'Anthology': 13, 'Encyclopedias': 14, 'Drama': 15, 'Mystery': 16, 'History': 17,
    'Science': 18, 'Dictionaries': 19, 'Diaries': 20, 'Religion-Spirituality': 21, 'Action and Adventure': 22,
    'Poetry': 23, 'Cookbooks': 24, 'Comics': 25, 'Art': 26, 'Travel': 27, 'Series': 28, 'Math': 29, 'Romance': 30}},inplace=True)



## encoding "Management or Technical" column.
data.replace({'Management or Technical':{'Management': 0, 'Technical': 1}},inplace=True)



## encoding "hard/smart worker" column.
data.replace({'hard/smart worker':{'hard worker': 0, 'smart worker': 1}},inplace=True)



## encoding "worked in teams ever?" column.
data.replace({'worked in teams ever?':{'yes': 1, 'no': 0}},inplace=True)



## encoding "Introvert" column.
data.replace({'Introvert':{'yes': 1, 'no': 0}},inplace=True)


In [45]:
##  Encoding "Suggested Job Role" column.

data.replace({'Suggested Job Role' : {'Network Security Engineer': 0, 'Software Engineer': 1, 'UX Designer': 2, 'Software Developer': 3,
    'Database Developer': 4, 'Software Quality Assurance (QA) / Testing': 5, 'Web Developer': 5,
    'CRM Technical Developer': 6, 'Technical Support': 7, 'Systems Security Administrator': 8,
    'Applications Developer': 9, 'Mobile Applications Developer': 10}}, inplace=True)

In [47]:
X = data.drop(columns='Suggested Job Role', axis=1)
Y = data['Suggested Job Role']

In [19]:
print(X)

      Logical quotient rating  hackathons  coding skills rating  \
0                           5           0                     6   
1                           7           6                     4   
2                           2           3                     9   
3                           2           6                     3   
4                           2           0                     3   
...                       ...         ...                   ...   
6896                        7           5                     6   
6897                        6           5                     1   
6898                        5           1                     6   
6899                        1           6                     4   
6900                        5           6                     2   

      public speaking points  self-learning capability?  Extra-courses did  \
0                          2                          1                  1   
1                          3           

In [20]:
print(Y)

0       9
1       9
2       9
3       9
4       9
       ..
6896    5
6897    5
6898    5
6899    5
6900    5
Name: Suggested Job Role, Length: 6901, dtype: int64


In [16]:
data.head()

Logical quotient rating  hackathons  coding skills rating  \
0                        5           0                     6   
1                        7           6                     4   
2                        2           3                     9   
3                        2           6                     3   
4                        2           0                     3   

   public speaking points  self-learning capability?  Extra-courses did  \
0                       2                          1                  1   
1                       3                          1                  1   
2                       1                          1                  1   
3                       5                          1                  1   
4                       4                          1                  1   

   certifications  workshops  reading and writing skills  \
0               1          4                           0   
1               2          4                           2   
2               1          4                           2   
3               0          0                           2   
4               7          6                           2   

   memory capability score  Interested subjects  interested career area   \
0                        0                    3                        4   
1                        1                    8                        0   
2                        0                    6                        2   
3                        0                    4                        4   
4                        1                    0                        0   

   Type of company want to settle in?  Taken inputs from seniors or elders  \
0                                   2                                    0   
1                                   5                                    1   
2                                   6                                    1   
3                                   3                                    1   
4                                   2                                    0   

   Interested Type of Books  Management or Technical  hard/smart worker  \
0                        28                        0                  1   
1                         8                        1                  0   
2                        27                        1                  1   
3                         0                        0                  1   
4                         1                        1                  0   

   worked in teams ever?  Introvert  Suggested Job Role  
0                      1          0                   9  
1                      0          1                   9  
2                      0          0                   9  
3                      1          1                   9  
4                      1          0                   9

                    
                    Train the Model

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=2)

In [49]:
print(X.shape, X_train.shape, X_test.shape)

(6901, 19) (6210, 19) (691, 19)


In [50]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(random_state=1)
dtree.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=1)

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score

Y_pred = dtree.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
accuracy = accuracy_score(Y_test,Y_pred)
print("confusion matrics = ")
print(cm)
print("  ")
print("accuracy=",accuracy*10)

confusion matrics = 
[[ 9  4  8  4  6  8 11  4  8  5  5]
 [ 3  7  3  2  7 10  4  7  5  4  4]
 [ 9  5  8  5  5  6  8  6  7  5  6]
 [ 3  6  6  5  3 14  5  5  4  7  5]
 [10  8  3  3  6  7  4  3 10  6  6]
 [15 11 11  7  9 18 12  7  8 11  9]
 [ 5  3  4  4  3  7  2  5  8  6  2]
 [ 1  5  7  3  5  6  3  2  8  3  5]
 [ 4  3  4  5  3 12  1  7  1  3  4]
 [ 6  6  1  5  1  5  9  3  4  8  3]
 [ 2 12  7  1  4  8  3  5  2  4  3]]
  
accuracy= 0.9985528219971057


In [52]:
userdata = [['5','0','6','2','1','0','1','4','0','0','3','4','2','0','28','0','1','1','0']]
ynewclass = dtree.predict(userdata)
ynew = dtree.predict_proba(userdata)
print(ynewclass)
print("Probabilities of all classes: ", ynew)
print("Probability of Predicted class : ", np.max(ynew))

[9]
Probabilities of all classes:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Probability of Predicted class :  1.0


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [54]:
import pickle
pickle.dump(dtree,open('dtmodel.pkl','wb'))